[package]
name = "open_health_server"
version.workspace = true
edition = "2021"
license.workspace = true

[dependencies]
open_health_shared = { workspace = true }
open_health_db = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
